#
# This file is part of LiteDSP.
#
# Copyright (c) 2026 Florent Kermarrec <florent@enjoy-digital.fr>
# SPDX-License-Identifier: BSD-2-Clause

"""Vivado IP-Integrator packaging for generated LiteDSP flow cores.

The regular flow core deliberately exposes LiteX endpoint leaves (``payload_i``, ``payload_q``,
``first`` and ``last``) so generated Verilog remains pleasant to use outside a vendor tool.  IP
Integrator, however, needs canonical AXI4-Stream buses.  This module emits a small structural
wrapper that packs each endpoint payload into byte-aligned ``TDATA``, maps ``first`` to
``TUSER[0]`` and maps ``last`` to ``TLAST``.  A generated Tcl script then packages the wrapper,
the original core, ROM initialization files and software register maps as a checked IP-XACT core.
"""

import json
import os
import shutil
import subprocess


DEFAULT_PART = "xc7a200tsbg484-3"

_AXIL_CHANNELS = {
    "aw": ("valid", "ready", "addr"),
    "w":  ("valid", "ready", "data", "strb"),
    "b":  ("valid", "ready", "resp"),
    "ar": ("valid", "ready", "addr"),
    "r":  ("valid", "ready", "data", "resp"),
}


def _payload_fields(endpoint):
    """Return ``[(field_name, width)]`` in the endpoint's LSB-first payload order."""
    return [(name, len(getattr(endpoint, name)))
            for name, *_ in endpoint.description.payload_layout]


def _stream_interfaces(ip):
    out = []
    for direction, endpoints in (("slave", ip.chain.inputs), ("master", ip.chain.outputs)):
        for name, endpoint in endpoints.items():
            fields = _payload_fields(endpoint)
            payload_width = sum(width for _, width in fields)
            tdata_width = ((payload_width + 7)//8)*8
            out.append({
                "name": name,
                "direction": direction,
                "fields": fields,
                "payload_width": payload_width,
                "tdata_width": tdata_width,
            })
    return out


def _axis_prefix(interface):
    side = "s" if interface["direction"] == "slave" else "m"
    return f"{side}_axis_{interface['name']}"


def _port(direction, width, name):
    shape = "" if width == 1 else f" [{width - 1}:0]"
    return f"    {direction} wire{shape} {name}"


def _wrapper_verilog(core_name, wrapper_name, interfaces):
    ports = [
        _port("input", 1, "aclk"),
        _port("input", 1, "aresetn"),
    ]
    for interface in interfaces:
        p = _axis_prefix(interface)
        if interface["direction"] == "slave":
            ports += [
                _port("input", 1, f"{p}_tvalid"),
                _port("output", 1, f"{p}_tready"),
                _port("input", interface["tdata_width"], f"{p}_tdata"),
                _port("input", 1, f"{p}_tlast"),
                _port("input", 1, f"{p}_tuser"),
            ]
        else:
            ports += [
                _port("output", 1, f"{p}_tvalid"),
                _port("input", 1, f"{p}_tready"),
                _port("output", interface["tdata_width"], f"{p}_tdata"),
                _port("output", 1, f"{p}_tlast"),
                _port("output", 1, f"{p}_tuser"),
            ]

    # Canonical AXI4-Lite slave.
    axil_widths = {
        "awvalid": 1, "awready": 1, "awaddr": 16,
        "wvalid": 1, "wready": 1, "wdata": 32, "wstrb": 4,
        "bvalid": 1, "bready": 1, "bresp": 2,
        "arvalid": 1, "arready": 1, "araddr": 16,
        "rvalid": 1, "rready": 1, "rdata": 32, "rresp": 2,
    }
    slave_inputs = {"awvalid", "awaddr", "wvalid", "wdata", "wstrb", "bready",
                    "arvalid", "araddr", "rready"}
    for suffix, width in axil_widths.items():
        ports.append(_port("input" if suffix in slave_inputs else "output", width,
                           f"s_axi_{suffix}"))

    lines = [
        "// Machine-generated by LiteDSP; canonical AXI wrapper for Vivado IP Integrator.",
        f"module {wrapper_name}(",
        ",\n".join(ports),
        ");",
        "",
    ]

    # Separate wires make output payload packing legal in Verilog-2001 on every supported tool.
    for interface in interfaces:
        if interface["direction"] != "master":
            continue
        for field, width in interface["fields"]:
            shape = "" if width == 1 else f" [{width - 1}:0]"
            lines.append(f"wire{shape} {interface['name']}_payload_{field};")
        p = _axis_prefix(interface)
        packed = [f"{interface['name']}_payload_{name}"
                  for name, _ in reversed(interface["fields"])]
        padding = interface["tdata_width"] - interface["payload_width"]
        if padding:
            packed.insert(0, f"{padding}'d0")
        lines.append(f"assign {p}_tdata = {{{', '.join(packed)}}};")
    if any(i["direction"] == "master" for i in interfaces):
        lines.append("")

    connections = [
        "        .sys_clk(aclk)",
        "        .sys_rst(~aresetn)",
    ]
    for interface in interfaces:
        name = interface["name"]
        p = _axis_prefix(interface)
        connections += [
            f"        .{name}_valid({p}_tvalid)",
            f"        .{name}_ready({p}_tready)",
            f"        .{name}_first({p}_tuser[0])",
            f"        .{name}_last({p}_tlast)",
        ]
        bit = 0
        for field, width in interface["fields"]:
            if interface["direction"] == "slave":
                signal = f"{p}_tdata[{bit + width - 1}:{bit}]"
            else:
                signal = f"{name}_payload_{field}"
            connections.append(f"        .{name}_payload_{field}({signal})")
            bit += width
    for channel, fields in _AXIL_CHANNELS.items():
        for field in fields:
            connections.append(
                f"        .s_axil_{channel}{field}(s_axi_{channel}{field})")

    lines += [
        f"{core_name} core_i (",
        ",\n".join(connections),
        ");",
        "",
        "endmodule",
        "",
    ]
    return "\n".join(lines)


def _tcl_quote(value):
    return "{" + str(value).replace("}", "\\}") + "}"


def _map_port(bus, logical, physical):
    return [
        f"set port_map [ipx::add_port_map {logical} ${bus}]",
        f"set_property physical_name {physical} $port_map",
    ]


def _package_tcl(name, wrapper_name, part, clock_ns, interfaces):
    axis_names = [f"{'S' if i['direction'] == 'slave' else 'M'}_AXIS_{i['name'].upper()}"
                  for i in interfaces]
    associated = ":".join(["S_AXI"] + axis_names)
    lines = [
        "set root [file normalize [file dirname [info script]]]",
        "set work [file join $root .vivado_pack]",
        "file delete -force $work",
        f"create_project -force litedsp_pack $work -part {_tcl_quote(part)}",
        "set hdl_files [glob -nocomplain [file join $root hdl *.v]]",
        "add_files -norecurse $hdl_files",
        "set init_files [glob -nocomplain [file join $root hdl *.init]]",
        "if {[llength $init_files]} {",
        "    add_files -norecurse $init_files",
        "    set_property file_type {Memory Initialization Files} [get_files $init_files]",
        "}",
        f"set_property top {_tcl_quote(wrapper_name)} [current_fileset]",
        "update_compile_order -fileset sources_1",
        "ipx::package_project -root_dir $root -vendor enjoy-digital.fr -library litedsp -taxonomy /LiteDSP -import_files -set_current true",
        "set core [ipx::current_core]",
        f"set_property name {_tcl_quote(name)} $core",
        f"set_property display_name {_tcl_quote('LiteDSP ' + name)} $core",
        "set_property description {Generated LiteDSP AXI4-Stream processing chain with AXI4-Lite control} $core",
        "set_property version 1.0 $core",
        "set_property core_revision 1 $core",
        "set_property supported_families {artix7 Production artixuplus Production} $core",
        "",
        "# Remove any heuristic interfaces before adding deterministic mappings.",
        "foreach bus [ipx::get_bus_interfaces -of_objects $core] { ipx::remove_bus_interface [get_property NAME $bus] $core }",
        "",
        "set rst [ipx::add_bus_interface ARESETN $core]",
        "set_property abstraction_type_vlnv xilinx.com:signal:reset_rtl:1.0 $rst",
        "set_property bus_type_vlnv xilinx.com:signal:reset:1.0 $rst",
        "set_property interface_mode slave $rst",
        *_map_port("rst", "RST", "aresetn"),
        "set polarity [ipx::add_bus_parameter POLARITY $rst]",
        "set_property value ACTIVE_LOW $polarity",
        "",
        "set clk [ipx::add_bus_interface ACLK $core]",
        "set_property abstraction_type_vlnv xilinx.com:signal:clock_rtl:1.0 $clk",
        "set_property bus_type_vlnv xilinx.com:signal:clock:1.0 $clk",
        "set_property interface_mode slave $clk",
        *_map_port("clk", "CLK", "aclk"),
        "set assoc [ipx::add_bus_parameter ASSOCIATED_BUSIF $clk]",
        f"set_property value {_tcl_quote(associated)} $assoc",
        "set assoc_rst [ipx::add_bus_parameter ASSOCIATED_RESET $clk]",
        "set_property value ARESETN $assoc_rst",
        "set frequency [ipx::add_bus_parameter FREQ_HZ $clk]",
        f"set_property value {round(1e9/clock_ns)} $frequency",
        "",
        "set axil [ipx::add_bus_interface S_AXI $core]",
        "set_property abstraction_type_vlnv xilinx.com:interface:aximm_rtl:1.0 $axil",
        "set_property bus_type_vlnv xilinx.com:interface:aximm:1.0 $axil",
        "set_property interface_mode slave $axil",
    ]
    for channel, fields in _AXIL_CHANNELS.items():
        for field in fields:
            lines += _map_port("axil", (channel + field).upper(), f"s_axi_{channel}{field}")
    lines += [
        "set protocol [ipx::add_bus_parameter PROTOCOL $axil]",
        "set_property value AXI4LITE $protocol",
        "",
    ]
    for interface, bus_name in zip(interfaces, axis_names):
        var = "axis_" + interface["name"]
        prefix = _axis_prefix(interface)
        mode = interface["direction"]
        lines += [
            f"set {var} [ipx::add_bus_interface {bus_name} $core]",
            f"set_property abstraction_type_vlnv xilinx.com:interface:axis_rtl:1.0 ${var}",
            f"set_property bus_type_vlnv xilinx.com:interface:axis:1.0 ${var}",
            f"set_property interface_mode {mode} ${var}",
        ]
        for logical, physical in (("TVALID", f"{prefix}_tvalid"),
                                  ("TREADY", f"{prefix}_tready"),
                                  ("TDATA", f"{prefix}_tdata"),
                                  ("TLAST", f"{prefix}_tlast"),
                                  ("TUSER", f"{prefix}_tuser")):
            lines += _map_port(var, logical, physical)
        lines += [
            f"set bytes [ipx::add_bus_parameter TDATA_NUM_BYTES ${var}]",
            f"set_property value {interface['tdata_width']//8} $bytes",
            f"set has_last [ipx::add_bus_parameter HAS_TLAST ${var}]",
            "set_property value 1 $has_last",
            f"set user_width [ipx::add_bus_parameter TUSER_WIDTH ${var}]",
            "set_property value 1 $user_width",
            "",
        ]
    lines += [
        "ipx::create_xgui_files $core",
        "ipx::update_checksums $core",
        "ipx::check_integrity -quiet $core",
        "ipx::save_core $core",
        "close_project",
        "file delete -force $work",
        'puts "PACKAGED_COMPONENT=[file join $root component.xml]"',
        "exit",
        "",
    ]
    return "\n".join(lines)


def package_vivado(ip, verilog_path, package_dir, name=None, part=DEFAULT_PART, run_vivado=True,
                   timeout=600):
    """Create and optionally execute a Vivado IP-XACT packaging directory.

    Returns the expected ``component.xml`` path.  ``run_vivado=False`` is useful for portable
    generation/tests: the complete HDL, driver artifacts and reproducible packaging script are
    still emitted, while a licensed machine can execute ``package_ip.tcl`` later.
    """
    core_name = os.path.splitext(os.path.basename(verilog_path))[0]
    name = name or core_name
    wrapper_name = core_name + "_vivado"
    interfaces = _stream_interfaces(ip)
    hdl_dir = os.path.join(package_dir, "hdl")
    drivers_dir = os.path.join(package_dir, "drivers")
    os.makedirs(hdl_dir, exist_ok=True)
    os.makedirs(drivers_dir, exist_ok=True)

    source_dir = os.path.dirname(os.path.abspath(verilog_path))
    shutil.copy2(verilog_path, os.path.join(hdl_dir, os.path.basename(verilog_path)))
    for filename in sorted(os.listdir(source_dir)):
        source = os.path.join(source_dir, filename)
        if filename.endswith(".init") and os.path.isfile(source):
            shutil.copy2(source, os.path.join(hdl_dir, filename))
        elif filename in ("csr.csv", "csr.json", "csr.h", "blocks.json") and os.path.isfile(source):
            shutil.copy2(source, os.path.join(drivers_dir, filename))

    wrapper_path = os.path.join(hdl_dir, wrapper_name + ".v")
    with open(wrapper_path, "w", encoding="utf-8") as f:
        f.write(_wrapper_verilog(core_name, wrapper_name, interfaces))
    script_path = os.path.join(package_dir, "package_ip.tcl")
    with open(script_path, "w", encoding="utf-8") as f:
        f.write(_package_tcl(name, wrapper_name, part, ip.netlist.clock_ns, interfaces))
    with open(os.path.join(package_dir, "vivado_ip.json"), "w", encoding="utf-8") as f:
        json.dump({
            "name": name,
            "top": wrapper_name,
            "part": part,
            "clock_ns": ip.netlist.clock_ns,
            "interfaces": interfaces,
        }, f, indent=2, sort_keys=True)
        f.write("\n")

    component = os.path.join(package_dir, "component.xml")
    if run_vivado:
        if shutil.which("vivado") is None:
            raise RuntimeError("Vivado is required for --vivado-ip (use package_ip.tcl on a licensed host)")
        with open(os.path.join(package_dir, "package_ip.log"), "w", encoding="utf-8") as log:
            subprocess.run(["vivado", "-mode", "batch", "-source", "package_ip.tcl",
                            "-nojournal", "-nolog"], cwd=package_dir, stdout=log,
                           stderr=subprocess.STDOUT, check=True, timeout=timeout)
        if not os.path.exists(component):
            raise RuntimeError(f"Vivado produced no component.xml (see {package_dir}/package_ip.log)")
    return component
